config/routes.rb
Rails.application.routes.draw do
 
  resources :sourcetypes
  resources :referenceauthors
  resources :authors
  resources :references
   
  get 'static_pages/show'
  root 'static_pages#show'
  get ':page', to: 'static_pages#show', as: 'pages'





  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/referenceauthor.rb
class Referenceauthor < ApplicationRecord
   belongs_to :reference
   belongs_to :author
  
   def self.get_first_letter(str)
         str[0,1]
   end
   
   #Create Harvard Style Bibliography based on source tyoe
   def self.get_harvard_referencing(sourcetype,alastname,aname,publicationyear,title,series,edition,publicationplace,publisher,webaddress,accessdate,titleofconference)
   
      #Edit Series String
      unless series.to_s.strip.empty?
      series=series+" Series."
      end
      
      #Edit Edition String
      unless edition.to_s.strip.empty?
      edition=edition+" ed."
      end
      
      #Create Bibliography in Harvard Style for Books
      if(sourcetype=="Book")
         result=(alastname+", "+aname[0,1]+". ("+publicationyear.year.to_s+") <strong>"+title+"</strong> "+" "+series+" "+edition+" "+publicationplace+": "+publisher+".").html_safe
      end
      if(sourcetype=="Website")
         result=(aname+" ("+publicationyear.year.to_s+") "+title+" [Online] Available at: <"+ webaddress +"> [Accessed "+accessdate.day.to_s+" "+accessdate.month.to_s+" "+accessdate.year.to_s+"].")
      end
      if(sourcetype=="Conference Paper")
         result=(alastname+", "+aname[0,1]+". ("+publicationyear.year.to_s+") "+title+" ln: "+"<strong>"+titleofconference+"</strong> "+publicationplace+": "+publisher+".").html_safe
      end
      result
   end
 
end

app/controllers/referenceauthors_controller.rb
class ReferenceauthorsController < ApplicationController
  before_action :set_referenceauthor, only: [:show, :edit, :update, :destroy]

  # GET /referenceauthors
  # GET /referenceauthors.json
  def index
    @referenceauthors = Referenceauthor.all
  end

  # GET /referenceauthors/1
  # GET /referenceauthors/1.json
  def show
  end

  # GET /referenceauthors/new
  def new
    @referenceauthor = Referenceauthor.new
  end

  # GET /referenceauthors/1/edit
  def edit
  end

  # POST /referenceauthors
  # POST /referenceauthors.json
  def create
    @referenceauthor = Referenceauthor.new(referenceauthor_params)

    respond_to do |format|
      if @referenceauthor.save
        format.html { redirect_to @referenceauthor, notice: 'Referenceauthor was successfully created.' }
        format.json { render :show, status: :created, location: @referenceauthor }
      else
        format.html { render :new }
        format.json { render json: @referenceauthor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /referenceauthors/1
  # PATCH/PUT /referenceauthors/1.json
  def update
    respond_to do |format|
      if @referenceauthor.update(referenceauthor_params)
        format.html { redirect_to @referenceauthor, notice: 'Referenceauthor was successfully updated.' }
        format.json { render :show, status: :ok, location: @referenceauthor }
      else
        format.html { render :edit }
        format.json { render json: @referenceauthor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /referenceauthors/1
  # DELETE /referenceauthors/1.json
  def destroy
    @referenceauthor.destroy
    respond_to do |format|
      format.html { redirect_to referenceauthors_url, notice: 'Referenceauthor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_referenceauthor
      @referenceauthor = Referenceauthor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def referenceauthor_params
      params.require(:referenceauthor).permit(:author_id, :reference_id)
    end
end

app/helpers/referenceauthors_helper.rb
module ReferenceauthorsHelper
   def self.get_first_letter(str)
      puts str[0,1]
   end
end

app/views/referenceauthors/_form.html.erb
<%= form_for(referenceauthor) do |f| %>
  <% if referenceauthor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(referenceauthor.errors.count, "error") %> prohibited this referenceauthor from being saved:</h2>

      <ul>
      <% referenceauthor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.select :author_id, Author.all.collect {|t| [ t.name + " " +t.lastname, t.id ] }, {prompt: 'Select Author'} %>
  <%= f.select :reference_id, Reference.all.collect {|t| [ t.title, t.id ] }, {prompt: 'Select Reference'} %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/referenceauthors/edit.html.erb
<h1>Editing Referenceauthor</h1>

<%= render 'form', referenceauthor: @referenceauthor %>

<%= link_to 'Show', @referenceauthor %> |
<%= link_to 'Back', referenceauthors_path %>

app/views/referenceauthors/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('Attach Authors to References') %></h1>

<table>
  <thead>
    <tr>
       <th><%= t('SourceType') %></th>
      <th><%= t('Author') %></th>
      <th><%= t('Title') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @referenceauthors.each do |referenceauthor| %> 
      <tr>
      <td><%= Sourcetype.find_by(id: Reference.find_by(id: referenceauthor.reference_id).sourcetype_id).name %></td>
         <td><%= Author.find_by(id: referenceauthor.author_id ).name %> <%= Author.find_by(id: referenceauthor.author_id ).lastname %></td>
     
        <td><%= Reference.find_by(id: referenceauthor.reference_id).title %></td>
     
        <td><%= link_to t('Show Bibliography'), referenceauthor %></td>
        <td><%= link_to t('Edit'), edit_referenceauthor_path(referenceauthor) %></td>
        <td><%= link_to t('Destroy'), referenceauthor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('Attach New Reference'), new_referenceauthor_path %>

app/views/referenceauthors/new.html.erb
<h1>Attach Reference to Author</h1>

<%= render 'form', referenceauthor: @referenceauthor %>

<%= link_to 'Back', referenceauthors_path %>

app/views/referenceauthors/show.html.erb
<p id="notice"><%= notice %></p>
<table>
  <thead>
    <tr>
     <td><h2>Harvard Style Referencing</h2></td>
    </tr>
  </thead>
   <tbody>
     <tr>
        <td><%=Referenceauthor.get_harvard_referencing(Sourcetype.find_by(id: Reference.find_by(id: @referenceauthor.reference_id).sourcetype_id).name, Author.find_by(id: @referenceauthor.author_id ).lastname,Author.find_by(id: @referenceauthor.author_id ).name,Reference.find_by(id: @referenceauthor.reference_id).publicationYear,Reference.find_by(id: @referenceauthor.reference_id).title,Reference.find_by(id: @referenceauthor.reference_id).series,+Reference.find_by(id: @referenceauthor.reference_id).edition,Reference.find_by(id: @referenceauthor.reference_id).publicationplace,Reference.find_by(id: @referenceauthor.reference_id).publisher,Reference.find_by(id: @referenceauthor.reference_id).webadress,Reference.find_by(id: @referenceauthor.reference_id).accessdate,Reference.find_by(id: @referenceauthor.reference_id).titleofconference) %>
       
       </td>
        
     </tr>
       </tbody>
</table>

      
       


<%= link_to 'Edit', edit_referenceauthor_path(@referenceauthor) %> |
<%= link_to 'Back', referenceauthors_path %>