config/routes.rb
Rails.application.routes.draw do
 
  resources :sourcetypes
  resources :referenceauthors
  resources :authors
  resources :references
   
  get 'static_pages/show'
  root 'static_pages#show'
  get ':page', to: 'static_pages#show', as: 'pages'





  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reference.rb
class Reference < ApplicationRecord
   has_many :referenceauthors, dependent: :destroy
   has_many :authors, through: :referenceauthors
   belongs_to :sourcetype
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  before_action :set_reference, only: [:show, :edit, :update, :destroy]

  # GET /references
  # GET /references.json
  def index
    @references = Reference.all
  end

  # GET /references/1
  # GET /references/1.json
  def show
  end

  # GET /references/new
  def new
    @reference = Reference.new
  end

  # GET /references/1/edit
  def edit
  end

  # POST /references
  # POST /references.json
  def create
    @reference = Reference.new(reference_params)

    respond_to do |format|
      if @reference.save
        format.html { redirect_to @reference, notice: 'Reference was successfully created.' }
        format.json { render :show, status: :created, location: @reference }
      else
        format.html { render :new }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /references/1
  # PATCH/PUT /references/1.json
  def update
    respond_to do |format|
      if @reference.update(reference_params)
        format.html { redirect_to @reference, notice: 'Reference was successfully updated.' }
        format.json { render :show, status: :ok, location: @reference }
      else
        format.html { render :edit }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /references/1
  # DELETE /references/1.json
  def destroy
    @reference.destroy
    respond_to do |format|
      format.html { redirect_to references_url, notice: 'Reference was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reference
      @reference = Reference.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reference_params
      params.require(:reference).permit(:sourcetype_id, :publicationYear, :title, :series, :edition, :publicationplace, :publisher, :webadress, :accessdate, :titleofconference)
    end
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/views/references/_form.html.erb
<%= form_for(reference) do |f| %>
  <% if reference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reference.errors.count, "error") %> prohibited this reference from being saved:</h2>

      <ul>
      <% reference.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
     <%= f.select :sourcetype_id, Sourcetype.all.collect {|t| [ t.name, t.id ] }, {prompt: 'Select Source Type'} %>
  </div>

  <div class="field">
    <%= f.label :publicationYear %>
    <%= f.datetime_select :publicationYear, :discard_minute=> true , :discard_hour=> true  %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :series %>
    <%= f.text_field :series %>
  </div>

  <div class="field">
    <%= f.label :edition %>
    <%= f.text_field :edition %>
  </div>

  <div class="field">
    <%= f.label :publicationplace %>
    <%= f.text_field :publicationplace %>
  </div>

  <div class="field">
    <%= f.label :publisher %>
    <%= f.text_field :publisher %>
  </div>

  <div class="field">
    <%= f.label :webadress %>
    <%= f.text_field :webadress %>
  </div>

  <div class="field">
    <%= f.label :accessdate %>
    <%= f.datetime_select :accessdate, :discard_minute=> true , :discard_hour=> true%>
  </div>

  <div class="field">
    <%= f.label :titleofconference %>
    <%= f.text_field :titleofconference %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/references/edit.html.erb
<h1>Editing Reference</h1>

<%= render 'form', reference: @reference %>

<%= link_to 'Show', @reference %> |
<%= link_to 'Back', references_path %>

app/views/references/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('References') %></h1>

<table>
  <thead>
    <tr>
      <th><%= t('SourceType') %>&nbsp; </th>
      <th><%= t('Publication Year')%>&nbsp; </th>
      <th><%= t('Title')%>&nbsp;</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @references.each do |reference| %>
      <tr>
        <td><%= Sourcetype.find_by(id: Reference.find_by(id: reference.id).sourcetype_id).name %></td>
        <td><%= reference.publicationYear.year.to_s %></td>
        <td><%= reference.title %></td>
        <td><%= link_to t('Show'), reference %></td>
        <td><%= link_to t('Edit'), edit_reference_path(reference) %></td>
        <td><%= link_to t('Destroy'), reference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('New Reference'), new_reference_path %>

app/views/references/new.html.erb
<h1>New Reference</h1>

<%= render 'form', reference: @reference %>

<%= link_to 'Back', references_path %>

app/views/references/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sourcetype:</strong>
  <%= Sourcetype.find_by(id: Reference.find_by(id: @reference.id).sourcetype_id).name %>
</p>

<p>
  <strong>Publicationyear:</strong>
  <%= @reference.publicationYear %>
</p>

<p>
  <strong>Title:</strong>
  <%= @reference.title %>
</p>

<p>
  <strong>Series:</strong>
  <%= @reference.series %>
</p>

<p>
  <strong>Edition:</strong>
  <%= @reference.edition %>
</p>

<p>
  <strong>Publicationplace:</strong>
  <%= @reference.publicationplace %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @reference.publisher %>
</p>

<p>
  <strong>Webadress:</strong>
  <%= @reference.webadress %>
</p>

<p>
  <strong>Accessdate:</strong>
  <%= @reference.accessdate %>
</p>

<p>
  <strong>Titleofconference:</strong>
  <%= @reference.titleofconference %>
</p>

<%= link_to 'Edit', edit_reference_path(@reference) %> |
<%= link_to 'Back', references_path %>