config/routes.rb
Rails.application.routes.draw do
 
  resources :sourcetypes
  resources :referenceauthors
  resources :authors
  resources :references
   
  get 'static_pages/show'
  root 'static_pages#show'
  get ':page', to: 'static_pages#show', as: 'pages'





  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container" lang = <%= I18n.locale %> dir= <%= @local_dir %>>
  <nav>
    <ul class="nav navbar-nav navbar-left">
            <li><%= link_to t('Home'),   root_url %></li>
            <li><%= link_to t('help'),   pages_path('help') %></li>
            <li><%= link_to t('about'), pages_path('aboutus') %></li>
              <li><%= link_to t('languages.en'), root_url(locale: 'en'), html_options = { dir: "ltr", lang: "en" } %></li>
              <li><%= link_to t('languages.tr'), root_url(locale: 'tr'), html_options = { dir: "rtl", lang: "tr" } %></li>
              
          </ul>
  </nav>

   <small>
    <%= t('This Application is built by Mustafa Mete TUNCA') %>
  </small>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container" lang = <%= I18n.locale %> dir= <%= @local_dir %>>
        <%= link_to "Referencing Pro", root_url, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to t('References'),   references_path %></li>
            <li><%= link_to t('Source Types'),   sourcetypes_path %></li>
            <li><%= link_to t('Authors'), authors_path %></li>
            <li><%= link_to t('Attach Author to References'), referenceauthors_path %></li>
            
          </ul>
        </nav>
      </div>
    </header>
    
  

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
  <!DOCTYPE html>
<html lang="<%= I18n.locale %>"  dir= <%= @local_dir %> >
  <head>
   <title>Referencing Pro</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
   
  </head>

  <body>
     <%= render 'layouts/header' %>
     <div class="container">
    <%= yield %>
     <%= render 'layouts/footer' %>
    </div>
  </body>
</html>